language: rust

sudo: false

matrix:
  include:
    - rust: nightly

cache:
  - cargo

script:
  - cargo test --verbose

before_deploy:
  - cargo doc

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: false  
  local-dir: target/doc
  # Workaround for travis-ci/travis-ci#9312
  edge:
    branch: pages-ivar-set
  on:
    branch: master
